### ISSUE TITLE
 Activity A to  Activity B

### ISSUE THREAD

**Issue by zhangqifan1** [skydoves/TransformationLayout#1]
![1583029997038mza](https://user-images.githubusercontent.com/29973474/75618382-5c561480-5ba8-11ea-932a-9e8e2e85d778.gif)
it has a little shake  

Thanks for your library , could you please help me ,this is my  code

ActivityA:
`public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        TransitionExtensionKt.onTransformationStartContainer(this);

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        TextView tv = findViewById(R.id.tv);
        final TransformationLayout tLayout = findViewById(R.id.tLayout);

        tv.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Bundle bundle = tLayout.withActivity(MainActivity.this, "myTransitionName");
                Intent intent = new Intent(MainActivity.this, Main2Activity.class);
                intent.putExtra("TransformationParams", tLayout.getParcelableParams());
                startActivity(intent, bundle);
            }
        });

    }
}`

ActivityB:
`public class Main2Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        TransformationLayout.Params params = getIntent().getParcelableExtra("TransformationParams");
        TransitionExtensionKt.onTransformationEndContainer(this, params);

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

    }
}`

 minSdkVersion 21
  targetSdkVersion 29

What's the problem

**Comment by skydoves** [comment]
Hi, there is no problem with your code.
Could you test again using this attribute on your XML?

```gradle
app:transformation_pathMode="linear"
```

**Comment by zhangqifan1** [comment]
Yeah ! the problem have been solved, thanks
