### ISSUE TITLE
 Material latest version is not supported 

### ISSUE THREAD

**Issue by AydroidDev** [skydoves/TransformationLayout#10]
I am currently using the implementation 'com.google.android.material: material: 1.3.0-alpha01' but there is something wrong with it, I had difficulty applying it to my project. I downgraded to determine which version started after the problem and found that this library is running in the latest implementation 'com.google.android.material: material: 1.2.0-alpha06'. Please can you update the library according to the latest versions of addictions?

**Comment by skydoves** [comment]
Hi, Thank you for your issue.
Unfortunately, there are some delaying bugs in material `1.3.0-alpoha01` in the motion system, so I can't migrate it now. I left an issue and trying to find what is the problem. If I find or the bugs are fixed in the later versions, I will let you know.

**Comment by AydroidDev** [comment]
yes, I think I know what the problem is. But even if I use it in this form, 1.2.0-alpha06, my project has problems and I have a project written in Andorid x and Java. So I couldn't use the codes in any way. Java Class is ridiculous after adding codes as it is having trouble importing

**Comment by Android-wangmeng** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/material/transition/MaterialContainerTransformSharedElementCallback;

**Comment by skydoves** [comment]
Hi, @AydroidDev @Android-wangmeng !
I just found the problem in the material `1.3.0-alpoha01`, It is fixed and will be released in the next version.
Thank you for your issue :)

**Comment by skydoves** [comment]
It is released a new version `1.0.5`!
Thank you for your issue :)
