### ISSUE TITLE
Duplicate Value

### ISSUE THREAD

**Issue by satriawarn** [skydoves/TransformationLayout#15]
Hi, i'm interesting with this library, but i got some error duplicate.
I'm already using google material 1.3.0-alpha01 and this library version is 1.0.5, so when i build my app some error came up.

![image](https://user-images.githubusercontent.com/33830500/89702693-1038a880-d96e-11ea-8e57-d6be49d7d562.png)

Could you tell me what is wrong with this? Thank you

**Comment by skydoves** [comment]
Hi, @ericsath.
This library uses `1.3.0-alpha02` in the latest version `1.0.5`, it seems to happen conflict when using the material versions.
I recommend adding dependency like below if you use another version of the material.

```gradle
implementation("com.github.skydoves:transformationlayout:$versions.transformationLayout") {
    exclude group: "com.google.android.material", module: 'material'
}
```
