### ISSUE TITLE
Transition for DialogFragment

### ISSUE THREAD

**Issue by XWayne** [skydoves/TransformationLayout#16]
Hey! This is awesome. As you mention in :https://github.com/skydoves/TransformationLayout/issues/8#issuecomment-639301730_ , how `DialogFragment` work? 
Thank you a lot .

This library can be used only between `View`, `Fragment`, `Activity`, and `DialogFragment`.
Thank you :)

_Originally posted by @skydoves in https://github.com/skydoves/TransformationLayout/issues/8#issuecomment-639301730_

**Comment by skydoves** [comment]
Hi, @XWayne.
It works the same way as `Fragment` because the `DialogFragment` extends  `Fragment` as a parent.

**Comment by XWayne** [comment]
Thanks . but I mean showing as a Dialog with transformation  , instead of a simple Fragment  

It just works as a plain Dialog without transformation  after changing that MainSingleDetailFragment extends DialogFragment

![image](https://user-images.githubusercontent.com/10448179/95580398-dbc69300-0a69-11eb-8488-dccdf7e0277a.png)

I am quite confused , thanks a lot .
