### ISSUE TITLE
Animation flashes when background is white

### ISSUE THREAD

**Issue by fefereliezer** [skydoves/TransformationLayout#17]
- Library Version  v1.0.6
- Multiple devices, and emulators

I'm using the animation from a button to an Activity, I tried both examples (with and without a bundle) as described in the readme, and when the background of the destination activity is dark (as all the examples are), it works fine, but when I leave the destinations activity background blank (white) it flashes for a moment.

**Comment by skydoves** [comment]
It is related to [this](https://github.com/material-components/material-components-android/issues/1689) issue.
It's recommended to use `1.0.2` for avoiding the issue.

**Comment by fefereliezer** [comment]
Thanks for the fast response!
I tried it with versions `1.0.2` ~ `1.0.4` and it crashes at `TransitionExtensionKt.onTransformationStartContainer(this);` in the first activity. 
```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/material/transition/MaterialContainerTransformSharedElementCallback;
        at com.skydoves.transformationlayout.TransitionExtensionKt.onTransformationStartContainer(TransitionExtension.kt:31)
```

**Comment by skydoves** [comment]
Use the material dependency version `1.2.0-alpha06`.

**Comment by fefereliezer** [comment]
Thanks, it's much better, but the image is still doubled as seen in the 2nd image

![1](https://user-images.githubusercontent.com/45770970/98807425-ed110f80-241a-11eb-839d-98eab1ceaafc.jpg)
![2](https://user-images.githubusercontent.com/45770970/98807452-f5694a80-241a-11eb-81ff-212b373ad1b4.jpg)
![3](https://user-images.githubusercontent.com/45770970/98807463-f8643b00-241a-11eb-99c5-49faf7523ad0.jpg)

**Comment by skydoves** [comment]
Please set any background color for your second activity.

**Comment by fefereliezer** [comment]
Thanks! It worked!
(any color except transparent)
