### ISSUE TITLE
API Level 19

### ISSUE THREAD

**Issue by nicemak** [skydoves/TransformationLayout#2]
Please support API level 19.

**Comment by nicemak** [comment]
@skydoves can you?

**Comment by skydoves** [comment]
Hi,
Motion is only available on API level 21 (Android 5.0 Lollipop) and up. Additionally, the transitions included in the motion library are built using the Android Framework Transition library (android.transition), not the AndroidX Transition library (androidx.transition). Make sure any Transition being used in conjunction with the transitions provided extends android.transition.* and not androidx.transition.*.
