### ISSUE TITLE
Nested transitions

### ISSUE THREAD

**Issue by Bryanx** [skydoves/TransformationLayout#23]
Say you have 3 activities: A, B and C

1. In activity A the user clicks to start activity B. 
2. In activity B the user clicks to start Activity C.
3. Now the user presses back twice.

How can you preserve the first transition?

**Comment by skydoves** [comment]
Hi, @Bryanx 
TransformationLayout is implemented based on the `material-components`. 
So for resolving this issue, we should create an issue for the [material-component] team.
Thanks for share this issue!
