### ISSUE TITLE
Animation is misplaced and jitters abnormally

### ISSUE THREAD

**Issue by sangsais** [skydoves/TransformationLayout#25]
- Library Version [ v1.0.8]
- Affected Device(s) [Redmi Note4  with Android 6.0]
 
Run the demo on the latest master to reproduce

https://user-images.githubusercontent.com/6415942/115809604-fcab7000-a41e-11eb-9440-2d4d7ad5ae58.mp4

**Comment by skydoves** [comment]
Hi, that seems an internal bug in the [material-components-android](https://github.com/material-components/material-components-android/issues?q=transform).

**Comment by sangsais** [comment]
thanks
