### ISSUE TITLE
how to use between fragment?

### ISSUE THREAD

**Issue by sunyimeng** [skydoves/TransformationLayout#3]
as title

**Comment by skydoves** [comment]
@sunyimeng 
Hi, I'm thinking about the new feature of the fragment.
If I release a new version, I will let you know!
Thank you :)

**Comment by skydoves** [comment]
@sunyimeng 
Hi, it is released in the new version [1.0.4](https://github.com/skydoves/TransformationLayout/releases/tag/1.0.4).
Thank you for your issue :)
