### ISSUE TITLE
Navigation UI

### ISSUE THREAD

**Issue by ebekerman** [skydoves/TransformationLayout#4]
Does it work with Navigation Component?

**Comment by skydoves** [comment]
Hi, @ebekerman sorry for the late reply.
Here is the navigation solution.

You can replace the [getBundle and addTransformation section](https://github.com/skydoves/transformationlayout#getbundle-and-addtransformation) using below codes.
```kotlin
// Map the start View in FragmentA and the transitionName of the end View in FragmentB
val extras = FragmentNavigatorExtras(view to "TransformationParams")
findNavController().navigate(R.id.action_fragmentA_to_fragmentB, null, null, extras)
```
And the other settings are the same.
