### ISSUE TITLE
Material design dependency

### ISSUE THREAD

**Issue by Prince-Predator3** [skydoves/TransformationLayout#5]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

Library version 1.0.4

The Google material dependency for this library is stated 1.2.0 alpha 6 which is breaking the login /signup activity of my app, which is made with version 1.0.0.

How do i solve this?

**Comment by skydoves** [comment]
You must use over the `1.2.0-alpha5` version of the material.
It is not supported in the lower version.
