### ISSUE TITLE
Fragment to another fragment but different activity

### ISSUE THREAD

**Issue by fjr619** [skydoves/TransformationLayout#9]
is this libs support Fragment to another fragment but different activity?

**Comment by skydoves** [comment]
In this case, just a transform view on the fragment into activity will work.

**Comment by fjr619** [comment]
can you give me example to do that? thank you

**Comment by skydoves** [comment]
Hi @fjr619.
You can find example codes in the [demo project](https://github.com/skydoves/TransformationLayout/tree/master/app/src/main/java/com/skydoves/transformationlayoutdemo).
Thank you :)

**Comment by fjr619** [comment]
so `onTransformationStartContainer` on fragment A, then `onTransformationEndContainer` Activity B that have fragment B? is it what you mean by `transform a view on the fragment into activity will work`?

**Comment by skydoves** [comment]
Yes, it is the same as `Fragment to another fragment but different activity`. Fragment or View to an another Activity has another Fragment. Fragment A (Included in Activity A) to Fragment B  (Included in Activity B) right?
